name: demetiapp
description: "ToDo app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  flutter_localizations:
    sdk: flutter
  logger: ^2.3.0
  dartz: ^0.10.1
  dio: ^5.4.3+1
  path_provider: ^2.0.15
  uuid: ^4.4.0
  sqflite: ^2.3.3+1
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3
  provider: ^6.1.2
  get_it: ^7.7.0
  injectable: ^2.4.2
  sizer: ^2.0.15
  device_preview: ^1.2.0
  firebase_crashlytics: ^4.0.3
  firebase_core: ^3.2.0
  firebase_remote_config: ^5.0.3
  firebase_analytics: ^11.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  injectable_generator: ^2.6.1
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  bloc_test: ^9.1.7


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icons/light/app_logo_light.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/app_icons/light/
    - assets/app_samples/

flutter_intl:
  enabled: true
