// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8Ih3iQRVME-yDhWnjqiyN6m9ntApOaI',
    appId: '1:848416640005:web:513ea73fcf249905bb606c',
    messagingSenderId: '848416640005',
    projectId: 'dementiapp-128d4',
    authDomain: 'dementiapp-128d4.firebaseapp.com',
    storageBucket: 'dementiapp-128d4.appspot.com',
    measurementId: 'G-92CW9PSSND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7hUf_dzQVU3uH2REI4lQlUq4IhossnCs',
    appId: '1:848416640005:android:ca5be5f44a87ae91bb606c',
    messagingSenderId: '848416640005',
    projectId: 'dementiapp-128d4',
    storageBucket: 'dementiapp-128d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAncdfeEBS0mxuOjH0xn3BSSZ12Z_ranu0',
    appId: '1:848416640005:ios:460bbe4dde8e017abb606c',
    messagingSenderId: '848416640005',
    projectId: 'dementiapp-128d4',
    storageBucket: 'dementiapp-128d4.appspot.com',
    iosBundleId: 'com.example.demetiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAncdfeEBS0mxuOjH0xn3BSSZ12Z_ranu0',
    appId: '1:848416640005:ios:460bbe4dde8e017abb606c',
    messagingSenderId: '848416640005',
    projectId: 'dementiapp-128d4',
    storageBucket: 'dementiapp-128d4.appspot.com',
    iosBundleId: 'com.example.demetiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN8Ih3iQRVME-yDhWnjqiyN6m9ntApOaI',
    appId: '1:848416640005:web:445c3b34af904366bb606c',
    messagingSenderId: '848416640005',
    projectId: 'dementiapp-128d4',
    authDomain: 'dementiapp-128d4.firebaseapp.com',
    storageBucket: 'dementiapp-128d4.appspot.com',
    measurementId: 'G-4ZSZLV1CL7',
  );
}
