name: workflow

on:
  push:
    branches: ['**']

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: flutter pub get
      - run: dart format .
      - run: dart fix --dry-run
      - run: dart fix --apply
      - run: flutter test
      - run: flutter build apk --release