name: workflow

on:
  push:
    branches: ['**']

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up key.properties
        run: echo "$KEY_PROPERTIES" > "$GITHUB_WORKSPACE/android/key.properties"
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      - name: Copy keystore file
        run: cp path/to/upload-keystore.jks $GITHUB_WORKSPACE/upload-keystore.jks
        
      - run: flutter pub get
      - run: dart format .
      - run: dart fix --dry-run
      - run: dart fix --apply
      - run: flutter test
      - run: flutter build apk --release